name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Get Coverage
        id: coverage
        run: |
          COVERAGE=$(node -p "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json')).total.lines.pct")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Create badges directory
        run: mkdir -p .github/badges

      - name: Generate coverage badge
        run: |
          curl -o .github/badges/coverage.svg \
          "https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.percentage }}%25-${{ steps.coverage.outputs.percentage >= 80 && 'brightgreen' || steps.coverage.outputs.percentage >= 70 && 'yellow' || 'red' }}"

      - name: Upload coverage reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Commit and push badge to badges branch
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Save current coverage and badge files
          mkdir -p /tmp/coverage-backup
          cp -r coverage/* /tmp/coverage-backup/
          mkdir -p /tmp/badges-backup
          cp -r .github/badges/* /tmp/badges-backup/
          
          # Switch to badges branch
          git fetch
          git checkout badges 2>/dev/null || git checkout -b badges
          
          # Clean and restore files
          git rm -rf . || true
          git clean -fxd
          mkdir -p .github/badges coverage
          cp -r /tmp/coverage-backup/* coverage/
          cp -r /tmp/badges-backup/* .github/badges/
          
          # Commit and force push
          git add -f .github/badges/coverage.svg coverage/
          git commit -m "Update coverage badge and reports" || exit 0
          git push -f origin badges