name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: |
          touch googleDriveCredentials.json
          npm test -- --coverage

      - name: Get Coverage
        id: coverage
        run: |
          COVERAGE=$(node -p "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json')).total.lines.pct")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Create badges directory
        run: mkdir -p .github/badges

      - name: Generate coverage badge
        run: |
          curl -o .github/badges/coverage.svg \
          "https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.percentage }}%25-${{ steps.coverage.outputs.percentage >= 80 && 'brightgreen' || steps.coverage.outputs.percentage >= 70 && 'yellow' || 'red' }}"

      - name: Upload coverage reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Commit and push badge
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge" || exit 0
          git push