name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Create badges directory
        run: mkdir -p .github/badges

      - name: Get Coverage
        id: coverage
        run: |
          COVERAGE=$(node -p "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json')).total.lines.pct")
          COLOR=$(node -e "const c = parseFloat('$COVERAGE'); process.stdout.write(c > 90 ? 'green' : c > 70 ? 'yellow' : 'red')")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT

      - name: Generate coverage badge
        uses: jossef/action-badge@v2.0.1
        with:
          icon: coverage
          label: coverage
          message: ${{ steps.coverage.outputs.percentage }}%
          color: ${{ steps.coverage.outputs.color }}
          path: .github/badges/coverage.svg

      - name: Upload coverage reports to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Commit and push badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge" || exit 0
          git push